// Off-chain prover script using Noir CLI output
import fs from 'fs';

/**
 * Reads a Noir proof generated by the CLI and returns it as a JS object.
 * @param proofPath Path to the proof file (e.g., 'zk_noir/score_proof.proof')
 */
function readScoreProof(proofPath: string) {
    const proof = JSON.parse(fs.readFileSync(proofPath, 'utf-8'));
    return proof;
}

// Example usage:
// const proof = readScoreProof('zk_noir/score_proof.proof');
// console.log(proof);
